FROM openjdk:17-jdk-alpine

WORKDIR /app

EXPOSE 8080

COPY target/Casinop2p-0.0.1-SNAPSHOT.jar /app/Casinop2p-0.0.1-SNAPSHOT.jar


# Run the application
CMD ["java", "-jar", "/app/tu-aplicacion.jar"]